spring.application.name=NOTIFICATION-SERVICE

server.port=8087

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/NotificationService}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.routes[0].id=notification-service
spring.cloud.gateway.routes[0].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/notification-service/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1


management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
